#!/usr/bin/env bash
# Switch active broker profile and optionally force-login + install file bridge.
#
# Usage:
#   ./scripts/16-use-broker.sh wsf              # print export lines + write .env.broker
#   ./scripts/16-use-broker.sh vantage
#   ./scripts/16-use-broker.sh wsf --login      # also run 13-force-login-bridge.sh
#   ./scripts/16-use-broker.sh vantage --login
#
# Requires MT5_PASSWORD in the environment (or in repo .env) for --login.
# Never prints the password.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

DO_LOGIN=0
BROKER=""
for arg in "$@"; do
  case "$arg" in
    --login) DO_LOGIN=1 ;;
    -h|--help)
      echo "Usage: $0 <broker> [--login]"
      echo "Profiles: config/brokers/*.env (e.g. wsf, vantage)"
      echo "See docs/MULTI-BROKER-MT5.md — one install is not every broker."
      exit 0
      ;;
    -*)
      die "unknown option: $arg"
      ;;
    *)
      if [[ -z "$BROKER" ]]; then
        BROKER="$arg"
      else
        die "unexpected argument: $arg"
      fi
      ;;
  esac
done
[[ -n "$BROKER" ]] || die "Usage: $0 <broker> [--login]"

PROFILE="$REPO_ROOT/config/brokers/${BROKER}.env"
if [[ ! -f "$PROFILE" ]]; then
  echo "error: missing profile: $PROFILE" >&2
  echo "Available:" >&2
  for f in "$REPO_ROOT"/config/brokers/*.env; do
    [[ -f "$f" ]] || continue
    echo "  $(basename "$f" .env)" >&2
  done
  die "Usage: $0 <broker> [--login]  (profiles in config/brokers/*.env)"
fi

# shellcheck disable=SC1090
set -a
source "$PROFILE"
set +a

# Overlay password from repo .env if present and not already set
load_dotenv

# Reject placeholder passwords for --login
if [[ "$DO_LOGIN" -eq 1 ]]; then
  [[ -n "${MT5_PASSWORD:-}" ]] || die "MT5_PASSWORD not set (export it or put real value in .env)"
  case "${MT5_PASSWORD}" in
    your_mt5_password_here|changeme|password|secret|'')
      die "MT5_PASSWORD looks like a placeholder — set the real master password for $BROKER"
      ;;
  esac
fi

# Persist active selection (no password) for convenience
ACTIVE="$REPO_ROOT/.env.broker"
cat >"$ACTIVE" <<EOF
# Generated by scripts/16-use-broker.sh — active broker selection (no password).
# Source: source .env.broker
# Or:     set -a; source config/brokers/${BROKER}.env; set +a
BROKER=${BROKER}
WINEPREFIX=${WINEPREFIX}
WINEARCH=${WINEARCH:-win64}
MT5_BACKEND=${MT5_BACKEND:-file}
MT5_LOGIN=${MT5_LOGIN}
MT5_SERVER=${MT5_SERVER}
MT5_BRIDGE_MAX_AGE=${MT5_BRIDGE_MAX_AGE:-60}
EOF

info "Active broker: $BROKER"
info "  WINEPREFIX=$WINEPREFIX"
info "  MT5_LOGIN=$MT5_LOGIN"
info "  MT5_SERVER=$MT5_SERVER"
info "  wrote $ACTIVE (no password)"

if [[ ! -x "$WINEPREFIX/drive_c/Program Files/MetaTrader 5/terminal64.exe" ]] \
  && [[ ! -f "$WINEPREFIX/drive_c/Program Files/MetaTrader 5/terminal64.exe" ]]; then
  # resolve symlink
  if [[ ! -e "$WINEPREFIX/drive_c/Program Files/MetaTrader 5/terminal64.exe" ]]; then
    warn "terminal64 not found under $WINEPREFIX — install broker MT5 first"
  fi
fi

if [[ "$DO_LOGIN" -eq 1 ]]; then
  info "Running force-login for $BROKER (password not logged)"
  export WINEPREFIX MT5_LOGIN MT5_PASSWORD MT5_SERVER MT5_BACKEND
  unset MT5_TERMINAL_PATH
  "$SCRIPT_DIR/13-force-login-bridge.sh"
else
  cat <<EOF

Next:
  export MT5_PASSWORD='...'   # real master password for this account
  ./scripts/16-use-broker.sh $BROKER --login

  # or GUI login then:
  export WINEPREFIX=$WINEPREFIX MT5_BACKEND=file
  uv run mt5-arch account
EOF
fi
