#!/usr/bin/env bash
# Shared helpers for mt5-arch-integration scripts.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load .env if present (does not override already-exported vars).
load_dotenv() {
  local env_file="${1:-$REPO_ROOT/.env}"
  if [[ -f "$env_file" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$env_file"
    set +a
  fi
}

export_wine_env() {
  export WINEPREFIX="${WINEPREFIX:-$HOME/.mt5}"
  export WINEARCH="${WINEARCH:-win64}"
  # Reduce noise; keep GUI working
  export WINEDEBUG="${WINEDEBUG:--all}"
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: required command not found: $cmd" >&2
    return 1
  fi
}

info() { echo "==> $*"; }
warn() { echo "warning: $*" >&2; }
die()  { echo "error: $*" >&2; exit 1; }

find_terminal64() {
  local prefix="${WINEPREFIX:-$HOME/.mt5}"
  if [[ -n "${MT5_TERMINAL_PATH:-}" && -f "$MT5_TERMINAL_PATH" ]]; then
    echo "$MT5_TERMINAL_PATH"
    return 0
  fi
  if [[ -f "$REPO_ROOT/config/local.paths" ]]; then
    # shellcheck disable=SC1091
    source "$REPO_ROOT/config/local.paths"
    if [[ -n "${MT5_TERMINAL_PATH:-}" && -f "$MT5_TERMINAL_PATH" ]]; then
      echo "$MT5_TERMINAL_PATH"
      return 0
    fi
  fi
  local found
  found="$(find "$prefix" -type f -name 'terminal64.exe' 2>/dev/null | head -n 1 || true)"
  if [[ -n "$found" ]]; then
    echo "$found"
    return 0
  fi
  return 1
}

write_local_paths() {
  local terminal_path="$1"
  local server_path="${2:-}"
  mkdir -p "$REPO_ROOT/config"
  cat >"$REPO_ROOT/config/local.paths" <<EOF
# Generated by install scripts — do not commit.
MT5_TERMINAL_PATH="$terminal_path"
MT5_SERVER_EXE="$server_path"
WINEPREFIX="${WINEPREFIX:-$HOME/.mt5}"
EOF
  info "Wrote $REPO_ROOT/config/local.paths"
}

default_mt5_setup_candidates() {
  cat <<EOF
${MT5_SETUP:-}
$HOME/storage/Downloads/mt5setup.exe
$HOME/Downloads/mt5setup.exe
/tmp/mt5setup.exe
EOF
}

find_mt5_setup() {
  local candidate
  while IFS= read -r candidate; do
    [[ -z "$candidate" ]] && continue
    if [[ -f "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done < <(default_mt5_setup_candidates)
  return 1
}

mt5server_dir() {
  echo "${WINEPREFIX:-$HOME/.mt5}/drive_c/mt5linux"
}

mt5server_path() {
  echo "$(mt5server_dir)/mt5server.exe"
}
