#!/usr/bin/env bash
# Shared helpers for mt5-arch-integration scripts.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load .env if present. Does not override variables already set in the environment
# (so WINEPREFIX=~/.mt5-staging ./scripts/13-force-login-bridge.sh works).
load_dotenv() {
  local env_file="${1:-$REPO_ROOT/.env}"
  if [[ -f "$env_file" ]]; then
    local line key val
    while IFS= read -r line || [[ -n "$line" ]]; do
      # strip CR, skip blanks/comments
      line="${line//$'\r'/}"
      [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
      [[ "$line" != *=* ]] && continue
      key="${line%%=*}"
      val="${line#*=}"
      # trim key whitespace
      key="${key#"${key%%[![:space:]]*}"}"
      key="${key%"${key##*[![:space:]]}"}"
      [[ -z "$key" ]] && continue
      # strip optional surrounding quotes on value
      if [[ "$val" =~ ^\".*\"$ ]]; then val="${val:1:-1}"
      elif [[ "$val" =~ ^\'.*\'$ ]]; then val="${val:1:-1}"
      fi
      # skip if already set in environment
      if [[ -n "${!key+x}" ]]; then
        continue
      fi
      export "$key=$val"
    done <"$env_file"
  fi
}

export_wine_env() {
  export WINEPREFIX="${WINEPREFIX:-$HOME/.mt5}"
  export WINEARCH="${WINEARCH:-win64}"
  # Reduce noise; keep GUI working
  export WINEDEBUG="${WINEDEBUG:--all}"
}

# Ensure Wayland clipboard is visible to Wine/XWayland (Ctrl+V paste).
# Safe to call often; starts bridge if missing and does a one-shot sync.
ensure_clipboard_bridge() {
  local bridge="$REPO_ROOT/scripts/11-clipboard-bridge.sh"
  if [[ ! -x "$bridge" ]]; then
    return 0
  fi
  # Prefer not to fail start scripts if wl-paste/xclip missing
  if ! command -v wl-paste >/dev/null 2>&1 || ! command -v xclip >/dev/null 2>&1; then
    warn "clipboard bridge skipped (need wl-paste + xclip). Install: pacman -S wl-clipboard xclip"
    return 0
  fi
  # Keep WAYLAND_DISPLAY for the bridge (wine start scripts may unset it later)
  local saved_wl="${WAYLAND_DISPLAY:-}"
  if [[ -z "$saved_wl" ]]; then
    for sock in wayland-1 wayland-0; do
      if [[ -S "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/$sock" ]]; then
        saved_wl="$sock"
        break
      fi
    done
  fi
  DISPLAY="${DISPLAY:-:0}" WAYLAND_DISPLAY="$saved_wl" "$bridge" start >/dev/null 2>&1 || true
  DISPLAY="${DISPLAY:-:0}" WAYLAND_DISPLAY="$saved_wl" "$bridge" once >/dev/null 2>&1 || true
}

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: required command not found: $cmd" >&2
    return 1
  fi
}

info() { echo "==> $*"; }
warn() { echo "warning: $*" >&2; }
die()  { echo "error: $*" >&2; exit 1; }

find_terminal64() {
  # Always honor the active WINEPREFIX. config/local.paths and MT5_TERMINAL_PATH
  # may hardcode ~/.mt5 from an older install — only use them if they live under
  # the current prefix (never source local.paths; that used to clobber WINEPREFIX).
  local prefix="${WINEPREFIX:-$HOME/.mt5}"
  local candidate found local_term

  candidate="$prefix/drive_c/Program Files/MetaTrader 5/terminal64.exe"
  if [[ -f "$candidate" ]]; then
    echo "$candidate"
    return 0
  fi

  found="$(find "$prefix" -type f -name 'terminal64.exe' 2>/dev/null | head -n 1 || true)"
  if [[ -n "$found" ]]; then
    echo "$found"
    return 0
  fi

  if [[ -n "${MT5_TERMINAL_PATH:-}" && -f "$MT5_TERMINAL_PATH" ]]; then
    case "$MT5_TERMINAL_PATH" in
      "$prefix"/*)
        echo "$MT5_TERMINAL_PATH"
        return 0
        ;;
    esac
  fi

  if [[ -f "$REPO_ROOT/config/local.paths" ]]; then
    local_term="$(
      # shellcheck disable=SC1091
      MT5_TERMINAL_PATH=""
      source "$REPO_ROOT/config/local.paths" >/dev/null 2>&1 || true
      printf '%s' "${MT5_TERMINAL_PATH:-}"
    )"
    if [[ -n "$local_term" && -f "$local_term" ]]; then
      case "$local_term" in
        "$prefix"/*)
          echo "$local_term"
          return 0
          ;;
      esac
    fi
  fi

  return 1
}

write_local_paths() {
  local terminal_path="$1"
  local server_path="${2:-}"
  mkdir -p "$REPO_ROOT/config"
  cat >"$REPO_ROOT/config/local.paths" <<EOF
# Generated by install scripts — do not commit.
MT5_TERMINAL_PATH="$terminal_path"
MT5_SERVER_EXE="$server_path"
WINEPREFIX="${WINEPREFIX:-$HOME/.mt5}"
EOF
  info "Wrote $REPO_ROOT/config/local.paths"
}

default_mt5_setup_candidates() {
  cat <<EOF
${MT5_SETUP:-}
$HOME/storage/Downloads/mt5setup.exe
$HOME/Downloads/mt5setup.exe
/tmp/mt5setup.exe
EOF
}

find_mt5_setup() {
  local candidate
  while IFS= read -r candidate; do
    [[ -z "$candidate" ]] && continue
    if [[ -f "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done < <(default_mt5_setup_candidates)
  return 1
}

mt5server_dir() {
  echo "${WINEPREFIX:-$HOME/.mt5}/drive_c/mt5linux"
}

mt5server_path() {
  echo "$(mt5server_dir)/mt5server.exe"
}

# Hyprland 0.56+ evaluates `hyprctl dispatch` as Lua. Use `hyprctl eval`.
hypr_eval() {
  hyprctl eval "$1" >/dev/null 2>&1 || true
}

_hypr_safe_selector() {
  local sel="${1:-}"
  [[ -n "$sel" ]] || return 1
  case "$sel" in
    *\'*|*\\*)
      warn "refusing hypr selector with quotes: $sel"
      return 1
      ;;
  esac
  printf '%s' "$sel"
}

hypr_focus_window() {
  local sel
  sel="$(_hypr_safe_selector "${1:-}")" || return 0
  hypr_eval "hl.dispatch(hl.dsp.focus({ window = '${sel}' }))"
}

hypr_move_window_workspace() {
  local sel ws
  sel="$(_hypr_safe_selector "${1:-}")" || return 0
  ws="${2:-}"
  [[ -n "$ws" ]] || return 0
  hypr_eval "hl.dispatch(hl.dsp.window.move({ window = '${sel}', workspace = ${ws}, follow = true }))"
}

