#!/usr/bin/env python3
"""Generate mql5/Files/forex_sr_levels.csv from hand-drawn MT5 chart templates.

Offline research helper (plain ``python3``, not ``uv run``). Reads UTF-16LE
``.tpl`` files (BOM; UTF-8 fallback), extracts OBJ_HLINE (type=1) prices, maps
timeframe-name prefixes to relevance tiers, and writes an ASCII/LF CSV consumed
by ``ForexHtfPivotsFib.mq5``.

Default template directory: ``~/Projects/trading/manual-trading-agent/plantillas``
(override with env ``PLANTILLAS_DIR``). Default output: repo
``mql5/Files/forex_sr_levels.csv`` (override with ``-o`` / ``--out``).
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

TIER_RANK = {"HIGH": 3, "MED": 2, "LOW": 1}

# Name-prefix → (tier, canonical source_tf label in the CSV).
_TF_MAP: dict[str, tuple[str, str]] = {
    "MN": ("HIGH", "MN"),
    "MN1": ("HIGH", "MN1"),
    "MONTHLY": ("HIGH", "MONTHLY"),
    "W1": ("HIGH", "W1"),
    "WEEKLY": ("HIGH", "WEEKLY"),
    "D1": ("HIGH", "D1"),
    "DAILY": ("HIGH", "DAILY"),
    "H4": ("HIGH", "H4"),
    "H1": ("MED", "H1"),
    "M30": ("MED", "M30"),
    "M15": ("MED", "M15"),
    "M5": ("LOW", "M5"),
    "M1": ("LOW", "M1"),
}

_DEFAULT_TEMPLATES = (
    "plantilla nq.tpl",
    "zonas BTC.tpl",
    "zonas DXY.tpl",
    "zonas.tpl",
)


def _decode_tpl(path: Path) -> str:
    raw = path.read_bytes()
    if raw.startswith(b"\xff\xfe") or raw.startswith(b"\xfe\xff"):
        return raw.decode("utf-16")
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return raw.decode("utf-16")


def _tier_and_tf(prefix: str) -> tuple[str, str]:
    """Map an object name's leading timeframe token to (tier, source_tf)."""
    key = prefix.upper()
    if key in _TF_MAP:
        return _TF_MAP[key]
    # Unrecognised prefix → MED, keep original token for source_tf.
    return "MED", prefix


def parse_template(path: Path) -> tuple[str, list[tuple[float, str, str]]]:
    """Return (symbol, rows) where rows are (price, tier, source_tf) sorted by price.

    Only ``type=1`` (OBJ_HLINE) objects contribute. Duplicate prices within a
    symbol collapse to the strongest tier (HIGH > MED > LOW).
    """
    text = _decode_tpl(path)
    m = re.search(r"^symbol=(.*)$", text, re.MULTILINE)
    if not m:
        raise ValueError(f"no symbol= field in {path}")
    symbol = m.group(1).strip()
    if not symbol:
        raise ValueError(f"empty symbol= in {path}")

    best: dict[float, tuple[int, str, str]] = {}
    for om in re.finditer(r"<object>\s*(.*?)\s*</object>", text, re.DOTALL):
        fields: dict[str, str] = {}
        for line in om.group(1).splitlines():
            line = line.strip()
            if not line or "=" not in line:
                continue
            k, v = line.split("=", 1)
            fields[k] = v
        if fields.get("type") != "1":
            continue
        if "value1" not in fields:
            continue
        name = fields.get("name", "")
        parts = name.split()
        prefix = parts[0] if parts else "UNK"
        tier, source_tf = _tier_and_tf(prefix)
        price = float(fields["value1"])
        rank = TIER_RANK[tier]
        prev = best.get(price)
        if prev is None or rank > prev[0]:
            best[price] = (rank, tier, source_tf)

    rows = sorted(
        ((price, tier, tf) for price, (_, tier, tf) in best.items()),
        key=lambda row: row[0],
    )
    return symbol, rows


def generate(templates: list[Path]) -> str:
    """Build the full CSV text (ASCII, LF) for the given template paths."""
    lines = [
        "# forex_sr_levels.csv - generated by scripts/tpl_to_sr_levels.py",
        "# Static snapshot of hand-drawn MT5 template zones. Regenerate after re-drawing.",
        "# symbol,price,tier,source_tf   tier: HIGH=yellow MED=white LOW=blue",
    ]
    # Stable order matching historical output: sort by template filename.
    for path in sorted(templates, key=lambda p: p.name):
        if not path.is_file():
            raise FileNotFoundError(f"template not found: {path}")
        symbol, rows = parse_template(path)
        lines.append(f"# {path.name} -> {symbol}")
        for price, tier, source_tf in rows:
            lines.append(f"{symbol},{price:.8f},{tier},{source_tf}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    repo = Path(__file__).resolve().parents[1]
    default_plantillas = Path(
        os.environ.get(
            "PLANTILLAS_DIR",
            str(Path.home() / "Projects/trading/manual-trading-agent/plantillas"),
        )
    )
    parser = argparse.ArgumentParser(
        description="Generate forex_sr_levels.csv from MT5 .tpl horizontal lines."
    )
    parser.add_argument(
        "templates",
        nargs="*",
        help="optional template filenames or paths (default: the four zonas/nq templates)",
    )
    parser.add_argument(
        "-o",
        "--out",
        type=Path,
        default=repo / "mql5" / "Files" / "forex_sr_levels.csv",
        help="output CSV path (default: mql5/Files/forex_sr_levels.csv)",
    )
    parser.add_argument(
        "--plantillas-dir",
        type=Path,
        default=default_plantillas,
        help="directory containing .tpl files (env PLANTILLAS_DIR)",
    )
    args = parser.parse_args(argv)

    if args.templates:
        paths: list[Path] = []
        for item in args.templates:
            p = Path(item)
            if not p.is_file():
                p = args.plantillas_dir / item
            paths.append(p)
    else:
        paths = [args.plantillas_dir / name for name in _DEFAULT_TEMPLATES]

    text = generate(paths)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="ascii", newline="\n")
    print(f"Wrote {args.out} ({text.count(chr(10))} lines)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
